#!/bin/bash
# Scripts/bundle-prism.sh
#
# Downloads and bundles Prism.js with language definitions into a single JavaScript file.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
RESOURCES_DIR="$PROJECT_ROOT/Sources/Textual/Internal/Highlighter/Prism"
OUTPUT_FILE="$RESOURCES_DIR/prism-bundle.js"
TEMP_DIR=$(mktemp -d)

echo "📦 Bundling Prism.js and language definitions..."

# Prism CDN base URL (minified files)
PRISM_VERSION="1.29.0"
PRISM_CDN="https://cdnjs.cloudflare.com/ajax/libs/prism/$PRISM_VERSION"

# Core Prism (required)
PRISM_CORE="$PRISM_CDN/prism.min.js"

# Language definitions to include
# See: https://prismjs.com/#supported-languages
LANGUAGES=(
  # Web fundamentals
  "markup"          # HTML, XML, SVG
  "markup-templating"
  "css"
  "scss"
  "sass"
  "less"
  "javascript"
  "typescript"
  "jsx"
  "tsx"

  # Systems programming
  "clike"           # C-like (required for many languages)
  "c"
  "cpp"
  "rust"
  "go"
  "zig"

  # Apple ecosystem
  "swift"
  "objectivec"

  # JVM languages
  "java"
  "kotlin"
  "scala"
  "groovy"
  "clojure"

  # .NET ecosystem
  "csharp"
  "fsharp"

  # Scripting languages
  "python"
  "ruby"
  "php"
  "perl"
  "lua"

  # Functional languages
  "elixir"
  "erlang"
  "haskell"
  "ocaml"
  "reason"

  # Lisp dialects
  "lisp"
  "scheme"

  # Modern languages
  "dart"
  "crystal"

  # Shell & system
  "bash"
  "powershell"

  # Data & config
  "json"
  "yaml"
  "toml"
  "sql"

  # Markup & docs
  "markdown"
  "latex"

  # Web assembly & GPU
  "wasm"
  "wgsl"

  # Query languages
  "graphql"
  "sparql"

  # Other
  "diff"
  "git"
  "http"
  "regex"
  "docker"
  "nginx"
)

# Create resources directory if it doesn't exist
mkdir -p "$RESOURCES_DIR"

# Create temporary output file
echo "// Prism.js v$PRISM_VERSION - Bundled on $(date)" > "$TEMP_DIR/bundle.js"
echo "// Auto-generated by Scripts/bundle-prism.sh - DO NOT EDIT" >> "$TEMP_DIR/bundle.js"
echo "" >> "$TEMP_DIR/bundle.js"

# Download and append Prism core
echo "⬇️  Downloading Prism core..."
if ! curl -sS -f "$PRISM_CORE" >> "$TEMP_DIR/bundle.js"; then
  echo "❌ Failed to download Prism core"
  rm -rf "$TEMP_DIR"
  exit 1
fi
echo "" >> "$TEMP_DIR/bundle.js"

# Track successful downloads
SUCCESS_COUNT=0
FAILED_COUNT=0

# Download and append each language
for lang in "${LANGUAGES[@]}"; do
  # Skip comments
  [[ "$lang" =~ ^#.*$ ]] && continue

  echo "⬇️  Downloading language: $lang"
  LANG_URL="$PRISM_CDN/components/prism-$lang.min.js"

  # Try to download, skip if 404
  if curl -sS -f "$LANG_URL" >> "$TEMP_DIR/bundle.js" 2>/dev/null; then
    echo "" >> "$TEMP_DIR/bundle.js"
    ((SUCCESS_COUNT++))
  else
    echo "⚠️  Language '$lang' not found, skipping..."
    ((FAILED_COUNT++))
  fi
done

# Add helper function for token flattening
cat >> "$TEMP_DIR/bundle.js" << 'EOF'

// Helper function to flatten Prism tokens into simple objects
function flattenPrismTokens(tokens) {
  var result = [];

  function flatten(token, parentType) {
    if (typeof token === 'string') {
      if (token.length > 0) {
        result.push({ content: token, type: parentType || 'plain' });
      }
    } else if (Array.isArray(token)) {
      token.forEach(function(t) { flatten(t, parentType); });
    } else if (token && typeof token === 'object') {
      var type = token.type || parentType || 'plain';
      if (typeof token.content === 'string') {
        if (token.content.length > 0) {
          result.push({ content: token.content, type: type });
        }
      } else if (Array.isArray(token.content)) {
        token.content.forEach(function(t) { flatten(t, type); });
      } else if (token.content && typeof token.content === 'object') {
        flatten(token.content, type);
      }
    }
  }

  tokens.forEach(function(token) { flatten(token, null); });
  return result;
}

// Export tokenization function
function tokenizeCode(code, language) {
  try {
    var grammar = Prism.languages[language];
    if (!grammar) {
      return [{ content: code, type: 'plain' }];
    }
    var tokens = Prism.tokenize(code, grammar);
    return flattenPrismTokens(tokens);
  } catch (e) {
    return [{ content: code, type: 'plain' }];
  }
}
EOF

# Move to final location
mv "$TEMP_DIR/bundle.js" "$OUTPUT_FILE"

# Cleanup
rm -rf "$TEMP_DIR"

# Report size
SIZE=$(wc -c < "$OUTPUT_FILE" | xargs)
SIZE_KB=$((SIZE / 1024))

echo ""
echo "✅ Bundle created: $OUTPUT_FILE"
echo "📊 Bundle size: ${SIZE_KB}KB"
echo "📊 Languages downloaded: $SUCCESS_COUNT"
if [ $FAILED_COUNT -gt 0 ]; then
  echo "⚠️  Failed downloads: $FAILED_COUNT"
fi
echo ""
echo "🎉 Done! The bundle is ready to be committed to the repository."
